channels:
- conda-forge
dependencies:
- python=3.8.12
- pip<=21.1.1
- pip:
  - mlflow
  - botocore==1.27.59
  - cryptography==38.0.1
  - fsspec==2022.8.2
  - google-api-python-client==2.60.0
  - google-cloud-bigquery==2.34.4
  - google-cloud-storage==2.5.0
  - keras==2.9.0
  - pandas==1.4.4
  - pillow==9.2.0
  - scipy==1.9.1
  - tensorflow==2.9.2
name: mlflow-env
